# Generated by Django 4.2.7 on 2024-03-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DogsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed', models.CharField(max_length=150, unique=True, verbose_name='Порода')),
                ('main_img', models.ImageField(blank=True, null=True, upload_to='dogs_images', verbose_name='Изображение')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
        ),
    ]
