# Generated by Django 4.2.7 on 2024-03-15 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dogstable',
            table='dogstable',
        ),
    ]
