# Generated by Django 4.2.7 on 2024-03-15 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0002_alter_dogstable_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogsProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appearance', models.TextField(unique=True, verbose_name='Внешний вид')),
                ('character', models.TextField(unique=True, verbose_name='Характер')),
                ('care', models.TextField(unique=True, verbose_name='Уход')),
                ('illness', models.TextField(unique=True, verbose_name='Болезни')),
                ('img_1', models.ImageField(blank=True, null=True, upload_to='dogs_images', verbose_name='Изображение 1')),
                ('img_2', models.ImageField(blank=True, null=True, upload_to='dogs_images', verbose_name='Изображение 2')),
                ('img_3', models.ImageField(blank=True, null=True, upload_to='dogs_images', verbose_name='Изображение 3')),
                ('char_img', models.ImageField(blank=True, null=True, upload_to='dogs_images', verbose_name='Изображение характер')),
                ('ill_img', models.ImageField(blank=True, null=True, upload_to='dogs_images', verbose_name='Изображение болезни')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dogs.dogstable', verbose_name='Порода')),
            ],
            options={
                'db_table': 'dogsproperty',
            },
        ),
    ]
